theme = "tokyonight_day"

[editor]
scroll-lines = 5
line-number = "absolute"
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "file-type", "file-encoding", "file-line-ending", "position", "total-line-numbers"]

[editor.lsp]
auto-signature-help = false
display-inlay-hints = false
display-signature-help-docs = false

[editor.cursor-shape]
normal = "block"
select = "block"
insert = "bar"

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = " "

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = false
